# Generated by Django 4.1.5 on 2023-03-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
