# Generated by Django 4.1.5 on 2023-02-27 17:09

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку для категории', null=True, upload_to=core.utils.path_and_rename2)),
                ('category_slug', models.SlugField(default='', help_text='Перед вводом названия категории очистите это поле', unique=True, verbose_name='URl')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название подкатегории', max_length=255)),
                ('subcategory_slug', models.SlugField(default='', help_text='Перед вводом названия подкатегории очистите это поле', unique=True, verbose_name='URl')),
                ('categories', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название товара', max_length=100)),
                ('product_slug', models.SlugField(default='', help_text='Перед вводом названия продукта очистите это поле', max_length=100, unique=True, verbose_name='URl')),
                ('image', models.ImageField(blank=True, default='http://127.0.0.1:8000/media/product_images/11-02-2023_20-39.jpg', help_text='Загрузите картинку товара', null=True, upload_to=core.utils.path_and_rename)),
                ('description', models.TextField(blank=True, default='', help_text='Введите описание товара', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену', max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('is_discount', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('subcategories', models.ForeignKey(help_text='Выберите подкатегорию', on_delete=django.db.models.deletion.CASCADE, to='core.subcategory')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name', 'product_slug'),
                'index_together': {('id', 'product_slug')},
            },
        ),
    ]
