# Generated by Django 4.1.5 on 2023-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(default='000000', unique=True, verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_time',
            field=models.IntegerField(default=1, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_volume',
            field=models.FloatField(default=1, verbose_name='Вес/Объем'),
        ),
    ]
