# Generated by Django 4.1.5 on 2023-03-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_product_code_product_valid_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_percent',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_volume',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Вес/Объем'),
        ),
    ]
