# Generated by Django 4.1.5 on 2023-03-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_discount_percent_product_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('vacant_slug', models.SlugField(default='', unique=True, verbose_name='URL')),
                ('salary', models.IntegerField(verbose_name='Заработная плата')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Условия работы')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('duties', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Преимуществом будет')),
                ('key_skills', models.TextField(verbose_name='Ключевые навыки')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('title',),
            },
        ),
    ]
