# Generated by Django 4.1.5 on 2023-01-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(help_text='Статья или информация о сайте/компании'),
        ),
    ]
