# Generated by Django 4.1.5 on 2023-01-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
    ]
