# Generated by Django 4.1.5 on 2023-01-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
