# Generated by Django 4.1.5 on 2023-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_discount_remove_product_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена со скидкой'),
        ),
    ]
