# Generated by Django 4.1.5 on 2023-01-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_category_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='subcategory',
            index_together=set(),
        ),
    ]
