# Generated by Django 4.1.5 on 2023-03-18 00:10

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='category',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Загрузите прозрачную картинку для категории', null=True, upload_to=core.utils.path_and_rename3),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
