# Generated by Django 4.1.5 on 2023-01-27 15:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку для категории', upload_to=core.models.path_and_rename2),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку товара', upload_to=core.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку для подкатегории', upload_to=core.models.path_and_rename3),
        ),
    ]
