# Generated by Django 4.1.5 on 2023-03-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
