# Generated by Django 4.1.5 on 2023-01-30 18:37

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 31, 0, 37, 30, 371895)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку для категории', null=True, upload_to=core.models.path_and_rename2),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку товара', null=True, upload_to=core.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategories',
            field=models.ForeignKey(help_text='Выберите подкатегорию', on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
        ),
    ]
