# Generated by Django 4.1.5 on 2023-01-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='AboutCompany',
        ),
    ]
