# Generated by Django 4.1.5 on 2023-02-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_company_aboutcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='description',
            field=models.TextField(blank=True, default='Информация о сайте', help_text='Статья или информация о сайте/компании', null=True),
        ),
    ]
