# Generated by Django 4.1.5 on 2023-02-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_aboutcompany_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='URl'),
        ),
    ]
