# Generated by Django 4.1.5 on 2023-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', help_text='Перед вводом названия категории очистите это поле', unique=True, verbose_name='URl'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Перед вводом названия продукта очистите это поле', max_length=100, unique=True, verbose_name='URl'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text='Перед вводом названия подкатегории очистите это поле', unique=True, verbose_name='URl'),
        ),
    ]
