# Generated by Django 4.1.5 on 2023-02-19 12:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_product_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/product_images/11-02-2023_20-39.jpg', help_text='Загрузите картинку товара', null=True, upload_to=core.models.path_and_rename),
        ),
    ]
