# Generated by Django 4.1.5 on 2023-02-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCompany',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'product_slug'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='subcategory_slug',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'product_slug')},
        ),
    ]
