# Generated by Django 4.1.5 on 2023-03-25 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_remove_category_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество Товара')),
                ('product', models.ForeignKey(help_text='Добавить Продукт', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Passive', 'passive')], default='passive', max_length=7)),
                ('cost_per_delivery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('наличные', 'Наличные'), ('банковской картой при получении', 'Банковской картой при получении'), ('mBank', 'mBank')], default='наличные', max_length=32)),
                ('card_number', models.CharField(blank=True, default=690181313, help_text='введите номер банковской карты(необязательно)', max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)])),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=26)),
                ('delivery_comment', models.TextField(blank=True, default='', help_text='Комментарии к доставке', null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.deliverycost')),
            ],
        ),
    ]
